[workspace]
resolver = "2"
members = ["year-*/day-*"]

[workspace.dependencies]
glam = "0.24.2"
itertools = "0.12.0"
nom = "7.1.3"
rayon = "1.8.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
thiserror = "1.0.50"
clap = "4.4.10"